version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    ports:
      - "8080:8080"